### ISSUE TITLE
Innfelte fotnoter

### ISSUE THREAD

**Issue by omarandlorraine** [Ravatsaas/apen-bibel#3]
Jeg synes det ble bedre med fotnotene nederst på sida, [slik](https://github.com/omarandlorraine/apen-bibel/tree/fotnoter/Tekst/01%20F%C3%B8rste%20Mosebok/004.md), enn innfelt [sånn her](https://github.com/Ravatsaas/apen-bibel/blob/master/Tekst/01%20F%C3%B8rste%20Mosebok/004.md). Se vers 16 og 25.

Hvis du sier deg enig så fortsetter jeg med å flytte dem.

**Comment by Ravatsaas** [comment]
Enig i at de tar seg bedre ut nederst på siden. Jeg har gjort noe lignende på mange andre steder men har brukt extended markdown syntax for fotnoter (https://www.markdownguide.org/extended-syntax/)

Se eksempel på bruk her: [Tekst/23 Jesaja/055.md](https://github.com/omarandlorraine/apen-bibel/blob/fotnoter/Tekst/23%20Jesaja/055.md)
